apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:  
  POSTGRES_DB: {{ .Values.api.postgres_db | b64enc | quote }}
  POSTGRES_USER: {{ .Values.api.postgres_user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.api.postgres_password | b64enc | quote }}
