apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api
type: Opaque
data:
  PORT: {{ .Values.api.port | printf "%d" | b64enc | quote }}
  DATABASE_URL: {{ .Values.api.database_url | b64enc | quote }}
  POSTGRES_DB: {{ .Values.api.postgres_db | b64enc | quote }}
  POSTGRES_USER: {{ .Values.api.postgres_user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.api.postgres_password | b64enc | quote }}
